"""Secrets: age-encrypted JSON at rest, plus redaction for logs/errors.

`infra/secrets.age` holds a single JSON object (Hostinger token, Cloudflare
token, origin cert key, ...) encrypted with `age` against the recipients
listed in `infra/age-recipients.txt`. Plaintext only ever exists in memory:
it is never written to disk and never logged. Any text that might contain a
secret value should be passed through `redact()` before it is printed or
folded into an exception message.

A teammate may hold several age identities (some hardware/YubiKey-backed via
an age plugin) -- `$STACKBASE_AGE_IDENTITY` can name any identity file. This
module never inspects or parses it; it is passed straight to `age -i`.
"""

from __future__ import annotations

import json
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable

from stackbase.errors import StackError

_DEFAULT_IDENTITY = Path.home() / ".age" / "key.txt"
_REDACTED = "***REDACTED***"

DEPLOY_KEY_NAME = "deploy_ssh_key"


def redact(text: str, values: Iterable[str]) -> str:
    """Replace every occurrence of each non-empty value in `values` with a mask.

    Longest values are masked first. Callers pass every secret they hold at
    once, and when one secret contains another (a PEM private key whose
    base64 body happens to contain a short token, say) masking the short one
    first would chop the long one into fragments that no longer match --
    leaving most of the real secret on screen. Longest-first is the only
    order that cannot do that.

    Empty strings are skipped -- replacing "" would otherwise insert the mask
    between every character of `text`.
    """
    for value in sorted({value for value in values if value}, key=lambda v: (-len(v), v)):
        text = text.replace(value, _REDACTED)
    return text


def _identity_path() -> Path:
    override = os.environ.get("STACKBASE_AGE_IDENTITY")
    return Path(override) if override else _DEFAULT_IDENTITY


def _run_age(args: list[str], *, input_bytes: bytes | None = None) -> subprocess.CompletedProcess[bytes]:
    try:
        return subprocess.run(["age", *args], input=input_bytes, capture_output=True, check=False)
    except FileNotFoundError as exc:
        raise StackError(
            "the 'age' command was not found",
            "install age (e.g. `apt install age`, `brew install age`, or see https://age-encryption.org)",
        ) from exc


def _secrets_missing_hint(secrets_path: Path, recipients_path: Path) -> str:
    # Only the two API tokens are yours to paste. The origin certificate
    # and its private key are generated by stack-base itself and added to
    # this same file (as "origin_cert"/"origin_key") the first time it
    # runs -- never type those in by hand.
    return (
        "create it with (CLOUDFLARE_TOKEN is optional -- leave it empty to skip DNS and the "
        "TLS origin certificate; the server is then reachable by IP/SSH only):\n"
        "HOSTINGER_TOKEN=<paste here>\n"
        "CLOUDFLARE_TOKEN=<paste here, or leave empty>\n"
        'printf \'{"hostinger_token": "%s", "cloudflare_token": "%s"}\' '
        '"$HOSTINGER_TOKEN" "$CLOUDFLARE_TOKEN" '
        f"| age -R {recipients_path} -o {secrets_path}"
    )


def _deploy_missing_hint(deploy_path: Path, _recipients_path: Path) -> str:
    return (
        "create it with `./infra/up deploy-key init` -- that generates the key in RAM and writes "
        f"{deploy_path} (encrypted) plus infra/keys/deploy.pub (committed)"
    )


@dataclass(frozen=True)
class SecretsFile:
    """One age-encrypted JSON file plus the recipients file it is encrypted to.

    Two exist. `SECRETS_FILE` holds everything an operator needs to run
    `up` (API tokens, the origin TLS key, app_env, the R2 credentials).
    `DEPLOY_FILE` holds exactly one value -- the project's SSH deploy
    private key -- against a DIFFERENT, wider recipient list, so a machine
    that only needs to push releases (a NixOS build host) can be given an
    identity that unlocks the deploy door and nothing else. Everything
    that reads or writes either file goes through the same code path;
    only this descriptor changes.
    """

    name: str
    recipients_name: str
    missing_hint: Callable[[Path, Path], str]


SECRETS_FILE = SecretsFile("secrets.age", "age-recipients.txt", _secrets_missing_hint)
DEPLOY_FILE = SecretsFile("deploy.age", "deploy-recipients.txt", _deploy_missing_hint)


def load_secrets(infra_dir: Path, file: SecretsFile = SECRETS_FILE) -> dict[str, str]:
    """Decrypt `<infra_dir>/<file.name>` with the configured age identity.

    Returns the decrypted payload as a flat `{"key": "value"}` object. A
    missing file raises a `StackError` whose hint is the exact command to
    create that particular file.

    The identity is `$STACKBASE_AGE_IDENTITY` (or `~/.age/key.txt`) either
    way: on a laptop that is usually a YubiKey-backed plugin identity, on a
    build host it is a plain file identity listed ONLY in
    `deploy-recipients.txt`.
    """
    secrets_path = infra_dir / file.name
    recipients_path = infra_dir / file.recipients_name

    if not secrets_path.exists():
        raise StackError(f"{secrets_path} not found", file.missing_hint(secrets_path, recipients_path))

    identity_path = _identity_path()
    if not identity_path.exists():
        raise StackError(
            f"age identity {identity_path} not found",
            "set $STACKBASE_AGE_IDENTITY to your age identity file (any identity, including a "
            "YubiKey-backed plugin identity), or create ~/.age/key.txt",
        )

    result = _run_age(["-d", "-i", str(identity_path), str(secrets_path)])
    if result.returncode != 0:
        stderr = result.stderr.decode("utf-8", errors="replace").strip()
        detail = f" ({stderr})" if stderr else ""
        raise StackError(
            f"failed to decrypt {secrets_path}",
            f"check that {identity_path} is the right identity and is a recipient of {secrets_path}{detail}",
        )

    try:
        data = json.loads(result.stdout.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise StackError(
            f"{secrets_path} did not decrypt to valid JSON",
            f"re-create {file.name} from a flat JSON object -- it may have been corrupted or "
            "encrypted from something else",
        ) from exc

    if not isinstance(data, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in data.items()):
        raise StackError(
            f"{secrets_path} did not decrypt to a flat JSON object of strings",
            f're-create {file.name} from a JSON object like {{"key": "value"}} with no nesting',
        )

    return data


def save_secrets(infra_dir: Path, data: dict[str, str], file: SecretsFile = SECRETS_FILE) -> None:
    """Encrypt `data` as JSON to `<infra_dir>/<file.name>`; plaintext never touches disk.

    `age` writes to a same-directory temp file first
    (`<file.name>.<pid>.tmp`, created at mode 0600 with no window at a
    laxer mode -- `os.open` with `O_CREAT|O_EXCL` sets the mode atomically,
    and `age -o` writing into an already-existing file reuses that
    inode/mode rather than replacing it). Only once `age` has exited 0 and
    the temp file is non-empty is it `os.replace`d over the real file -- an
    atomic rename on the same filesystem. A crash or a failing `age`
    mid-write therefore can never truncate the only copy: the original file
    is untouched until the replace, and the temp file is removed on every
    failure path (M3, Fix round 1).
    """
    recipients_path = infra_dir / file.recipients_name
    secrets_path = infra_dir / file.name

    if not recipients_path.exists():
        raise StackError(
            f"{recipients_path} not found",
            f"create infra/{file.recipients_name} with one age public key per line "
            f"(one per person who should be able to decrypt {file.name})",
        )

    payload = json.dumps(data).encode("utf-8")
    tmp_path = secrets_path.parent / f"{file.name}.{os.getpid()}.tmp"

    # A stale temp file from a previous crash under the same pid (rare, but
    # possible across pid reuse) must not block this run from converging.
    tmp_path.unlink(missing_ok=True)
    fd = os.open(str(tmp_path), os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    os.close(fd)

    try:
        result = _run_age(["-R", str(recipients_path), "-o", str(tmp_path)], input_bytes=payload)
        if result.returncode != 0:
            stderr = result.stderr.decode("utf-8", errors="replace").strip()
            raise StackError(
                f"failed to encrypt secrets to {secrets_path}",
                stderr or f"check that {recipients_path} contains valid age public keys",
            )
        if tmp_path.stat().st_size == 0:
            raise StackError(
                f"failed to encrypt secrets to {secrets_path}",
                "age exited successfully but produced no output -- nothing on disk was changed",
            )
        os.replace(tmp_path, secrets_path)
    except BaseException:
        tmp_path.unlink(missing_ok=True)
        raise


def read_recipients(path: Path) -> list[str]:
    """Every non-blank, non-comment line of an age recipients file, stripped."""
    if not path.exists():
        raise StackError(
            f"{path} not found",
            f"create {path} with one age public key per line (lines starting with # are ignored)",
        )
    return [
        stripped
        for line in path.read_text(encoding="utf-8").splitlines()
        if (stripped := line.strip()) and not stripped.startswith("#")
    ]


def check_recipients_superset(infra_dir: Path) -> None:
    """`deploy-recipients.txt` must list every recipient `age-recipients.txt` does.

    The split exists so a build host can decrypt the deploy key WITHOUT
    being able to decrypt anything else -- never the other way round.
    Anyone who already holds every secret in the project must not silently
    lose the ability to deploy, so the deploy list is a strict superset.

    No `deploy-recipients.txt` at all means this project has not set up a
    deploy key yet: nothing to check, no warning -- `deploy-key init` is
    what creates both files together.

    An empty (comment-only) `deploy-recipients.txt` means the same thing.
    The template ships that file pre-populated with instructions and no
    keys, so it exists in every freshly scaffolded project well before a
    deploy key does. Widening the skip to cover this case cannot hide real
    drift either: `save_secrets` shells out to `age -R <recipients file>`,
    and age refuses outright on a recipients file with zero keys, so a
    `deploy.age` can never exist alongside an empty recipients list.
    """
    deploy_recipients_path = infra_dir / DEPLOY_FILE.recipients_name
    if not deploy_recipients_path.exists():
        return

    allowed = set(read_recipients(deploy_recipients_path))
    if not allowed:
        return

    secrets_recipients_path = infra_dir / SECRETS_FILE.recipients_name
    missing = [key for key in read_recipients(secrets_recipients_path) if key not in allowed]
    if not missing:
        return

    raise StackError(
        f"{deploy_recipients_path} is missing {len(missing)} recipient(s) that "
        f"{secrets_recipients_path} lists",
        "everyone who can decrypt secrets.age must also be able to decrypt deploy.age -- add "
        f"these line(s) to {deploy_recipients_path}, then run `./infra/up deploy-key init --rotate` "
        f"to re-encrypt it: {', '.join(missing)}",
    )


def register_private_key(private_key_text: str, register_secret: Callable[[str], None]) -> None:
    """Feed the private key's whole text, plus each base64 body line, into
    `register_secret` (F2, Fix round 1) -- before it is ever handed to
    anything that could echo it back.

    A PEM/OpenSSH private key is `-----BEGIN ...-----` / body lines /
    `-----END ...-----`; only the header/footer lines are non-secret. Each
    body line is registered individually (not just the joined whole) so that
    a partial echo of the key (e.g. one line of a remote command's stderr)
    is still masked, the same reasoning `reconcile.redaction_values` applies
    to `app_env`.
    """
    register_secret(private_key_text)
    for line in private_key_text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("-----"):
            continue
        if len(stripped) >= 8:
            register_secret(stripped)


def write_public_key(path: Path, content: str) -> None:
    """Write a PUBLIC key file atomically at 0644, creating its parent."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.parent / f".{path.name}.tmp"
    tmp.write_text(content, encoding="utf-8")
    tmp.chmod(0o644)
    tmp.replace(path)
