# Forced-command dispatcher for the `deploy` SSH door.
#
# Installed by nixos/deploy.nix as the `command=` target of EVERY key in
# stackbase.deploy.keys, wrapped there as:
#   restrict,command="<store path>/bin/stack-deploy-ssh" <key>
# `restrict` alone already denies PTY allocation, port/agent/X11
# forwarding, and ~/.ssh/rc execution for that key -- this script is what
# confines the COMMAND surface once a session channel is granted.
#
# Protocol (case-sensitive, exact word count per subcommand):
#   upload <version> <sha256>   -- reads a tarball from stdin
#   deploy <version>
#   rollback
#   status
#   colors
#   releases
# Anything else -- no command at all (a bare interactive login attempt),
# an unrecognised subcommand, the wrong number of words, or a word that
# fails its own strict pattern -- exits 2 with a usage line and has NO
# side effects.
#
# $SSH_ORIGINAL_COMMAND is attacker-controlled: it is the literal string
# the client passed after `ssh deploy@host`. It is NEVER eval'd and NEVER
# handed to a shell for re-parsing. A command containing a newline is
# rejected outright, explicitly, before anything else touches it -- `read
# -a` (used to split the rest) only ever reads up to the FIRST newline of
# its input, so without this check a command like "status\nid" would be
# silently truncated to just "status" (safe -- the "id" half is simply
# never examined or executed -- but not a match for the protocol's own
# contract that an embedded newline is refused). What's left after that
# check is split purely on IFS whitespace -- no globbing, no
# `$()`/backtick expansion, no interpretation of `;`, `&&`, or `|`. Every
# resulting word is then validated against a strict allowlist pattern
# BEFORE it is used for anything, including before the word count itself
# is trusted to match a known subcommand shape.

usage() {
  echo "usage: ssh deploy@<host> 'upload <version> <sha256> | deploy <version> | rollback | status | colors | releases'" >&2
}

# Substituted by nixos/deploy.nix at build time with the stack-deploy
# package's store path -- the one place tarball validation (sha256,
# member type/path safety, mode normalisation, refuse-overwrite) lives.
# This script never re-implements or duplicates any of it.
STACK_DEPLOY_BIN="@stackDeployBin@"

# STACK_MAX_UPLOAD_BYTES/STACK_STATE_DIR come from /etc/stackbase/deploy.env,
# generated by nixos/deploy.nix -- the same file stack-deploy itself
# sources. The literal defaults below are only a fallback for a deploy.env
# that predates these options.
if [ -f /etc/stackbase/deploy.env ]; then
  # shellcheck source=/dev/null
  # (the real path only exists on a stackbase node; nothing to lint here)
  source /etc/stackbase/deploy.env
fi
STACK_MAX_UPLOAD_BYTES="${STACK_MAX_UPLOAD_BYTES:-524288000}"
# Same state directory as stack-deploy.sh -- deliberately NOT
# /var/lib/stackbase itself (app-host.nix's exclusive, root:nginx domain).
STACK_STATE_DIR="${STACK_STATE_DIR:-/var/lib/stackbase-deploy}"
INCOMING_DIR="$STACK_STATE_DIR/incoming"

# Substituted by nixos/deploy.nix at build time from the SAME
# `versionRegex` binding that produces stack-deploy.sh's VERSION_GREP --
# one source of truth for vMAJOR.MINOR.PATCH (no leading zeros, no
# pre-release/build suffix), not a hand-copied duplicate kept in sync by a
# comment (Fix round 1, F3).
VERSION_RE='@versionRegex@'
SHA256_RE='^[0-9a-f]{64}$'

if [ -z "${SSH_ORIGINAL_COMMAND:-}" ]; then
  usage
  exit 2
fi

# Reject an embedded newline explicitly, rather than relying on `read`'s
# own behaviour of silently stopping at the first line: `read -a` (below)
# only ever reads UP TO the first newline of its input, so a command like
# "status\nid" would otherwise be silently truncated to just "status" and
# run successfully -- safe (the "id" half is simply never examined or
# executed, not "run and ignored"), but that's an incidental consequence
# of `read`'s line semantics, not a deliberate policy, and it doesn't
# match the protocol's own contract that a newline in the command is
# refused outright.
case "$SSH_ORIGINAL_COMMAND" in
  *$'\n'*)
    usage
    exit 2
    ;;
esac

read -r -a parts <<<"$SSH_ORIGINAL_COMMAND"

subcommand="${parts[0]:-}"
version=""
sha256=""

case "$subcommand" in
  upload)
    [ "${#parts[@]}" -eq 3 ] || { usage; exit 2; }
    version="${parts[1]}"
    sha256="${parts[2]}"
    [[ "$version" =~ $VERSION_RE ]] || { usage; exit 2; }
    [[ "$sha256" =~ $SHA256_RE ]] || { usage; exit 2; }
    ;;
  deploy)
    [ "${#parts[@]}" -eq 2 ] || { usage; exit 2; }
    version="${parts[1]}"
    [[ "$version" =~ $VERSION_RE ]] || { usage; exit 2; }
    ;;
  rollback | status | colors | releases)
    [ "${#parts[@]}" -eq 1 ] || { usage; exit 2; }
    ;;
  *)
    usage
    exit 2
    ;;
esac

# Every word is validated above; from here on we only ever exec a FIXED
# argv built from those already-validated words -- never the raw words
# from $SSH_ORIGINAL_COMMAND passed through verbatim into something that
# could re-interpret them.
if [ "$subcommand" = upload ]; then
  # F2 (Fix round 1): a UNIQUE per-connection temp file, not the fixed
  # "$version.tar.gz.partial" -> "$version.tar.gz" pair the first
  # implementation used. Two concurrent `upload`s of the SAME version used
  # to share those two fixed names -- no lock held while streaming, so
  # whichever session's EXIT trap fired first deleted the OTHER session's
  # still-in-flight or freshly-landed file out from under it. mktemp here
  # gives each session its own path, so two racing uploads never touch the
  # same file at all; the only place they can still collide is inside
  # `stack-deploy unpack`, which already takes the engine lock and refuses
  # to overwrite an existing release -- exactly one wins, the other fails
  # cleanly with "release already exists", and neither leaves a stray file
  # under incoming/. mktemp's own default mode (0600) is already what's
  # wanted here -- no client but the one that created it can even read the
  # bytes it's uploading while they're still in flight.
  tmp=$(mktemp "$INCOMING_DIR/${version}.XXXXXX.tar.gz") || {
    echo "✗ upload failed: could not create a temp file under $INCOMING_DIR" >&2
    exit 1
  }

  # Always removed afterwards, success or failure: this trap fires on
  # every exit path out of the rest of the script, including the `set -e`
  # abort triggered by a failing "$STACK_DEPLOY_BIN" unpack call below.
  # Only ever this session's OWN temp file -- never a name shared with
  # another session -- so one session's cleanup can never delete another
  # session's in-flight or already-handed-off upload.
  trap 'rm -f "$tmp"' EXIT

  # Stream stdin straight to disk, never buffered in memory. head -c
  # reads at most cap+1 bytes; if the client sends more, the resulting
  # file is still capped at exactly cap+1 bytes (head stops reading once
  # satisfied), so this is a bounded read regardless of how much the
  # client actually tries to push.
  #
  # M2 (Fix round 1): checked explicitly rather than left to a bare
  # `set -e` abort -- a write failure here (e.g. disk full) would
  # otherwise kill the script with no diagnostic at all beyond head's own
  # exit code.
  if ! head -c "$((STACK_MAX_UPLOAD_BYTES + 1))" >"$tmp"; then
    echo "✗ upload failed while writing to disk (disk full?) -- nothing was kept" >&2
    exit 1
  fi

  size=$(stat -c '%s' "$tmp")
  if [ "$size" -gt "$STACK_MAX_UPLOAD_BYTES" ]; then
    echo "✗ upload exceeds the ${STACK_MAX_UPLOAD_BYTES}-byte cap" >&2
    exit 1
  fi

  "$STACK_DEPLOY_BIN" unpack "$version" --tarball "$tmp" --sha256 "$sha256"
  exit 0
fi

case "$subcommand" in
  deploy) exec "$STACK_DEPLOY_BIN" deploy "$version" ;;
  rollback) exec "$STACK_DEPLOY_BIN" rollback ;;
  status) exec "$STACK_DEPLOY_BIN" status ;;
  colors) exec "$STACK_DEPLOY_BIN" colors ;;
  releases) exec "$STACK_DEPLOY_BIN" releases ;;
esac
